### ISSUE TITLE
ImportError: No module named flask_basicauth 

### ISSUE THREAD

**Issue by oceanpad** [jpvanhal/flask-basicauth#13]
I had installed  Flask-BasicAuth use:
```
sudo pip install Flask-BasicAuth
```
My code looks like this:
```
from flask import Flask, render_template
from flask_basicauth import BasicAuth

app = Flask(__name__)

app.config['BASIC_AUTH_USERNAME'] = 'john'
app.config['BASIC_AUTH_PASSWORD'] = 'matrix'
app.config['BASIC_AUTH_FORCE'] = True

basic_auth = BasicAuth(app)

@app.route('/')
@basic_auth.required
def secret_view():
    return render_template('404.html')

if __name__ == '__main__':
  app.run(host='0.0.0.0', port=3000)
```
But when I run it, The error is.
```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from flask_basicauth import BasicAuth
ImportError: No module named flask_basicauth
```

**Comment by cartacioS** [comment]
Hey did you find a fix for this?

**Comment by vackosar** [comment]
@cartacioS why do you use app.config['BASIC_AUTH_FORCE'] = True and at the same time @basic_auth.required?

For me if I set the force option then I don't need to use required decorator.

**Comment by rjkunde** [comment]
Just ran into this. My application was written in python3, but I experienced the error after: sudo python app.py, which ran it with python2. I made sure that basicAuth was installed using: sudo **pip3** install Flask-BasicAuth.

**Comment by raquelpaiva** [comment]
Hey guys, did you get solved this problem?  i had the same problem here " raceback (most recent call last):
  File "main.py", line 2, in <module>
    from flask_basicauth import BasicAuth
ModuleNotFoundError: No module named 'flask_basicauth'"
ANd i did install "sudo pip3 install Flask-BasicAuth" but, when i call "python main.py"  i had the same problem =(
